### PR TITLE
Fix copy & paste errors in docstrings.

### PR DESCRIPTION
**Pull request by maxalbert**

### CODE REVIEW

**Comment by jbednar** [comment]
Good catches!  But they'll need to be applied to the original source files, which will propagate to the generated .html automatically when the docs are built next.

**Comment by maxalbert** [comment]
Where do the "original source files" live, exactly? The tutorial notebooks in the regular holoviews repository are stored with their output stripped, so I can't see a way of fixing the typos in the Options tutorial there. (But I'm probably missing something obvious.)

**Comment by philippjfr** [comment]
There's no need to update the notebooks manually, they'll get built and updated automatically. What needs to be updated is the reference_data, which you have also done here. The correct process for that is rather involved:

```
cd /path/to/holoviews/
git submodule update --init
cd doc/reference_data
git checkout reference_data
cd ../nbpublisher
./test_notebooks.py holoviews --path=../Tutorials/Options.ipynb -r
# Repeat step using python3 
cd ../reference_data
git add -f holoviews_Options*
git commit -m "Updated Options reference_data"
cd ..
git add reference_data
git commit -m "Updated reference_data submodule reference"
git push
```

Let me know if you run into trouble. Should have these as developer instructions somewhere. It's a bit of a mess and it's okay if you don't want to go through it right now. The other issue is you need to make sure to have the right versions of everything. I'll add instructions like this somewhere, until then I can't possibly expect you to follow all this.

**Comment by jbednar** [comment]
Maybe I'm jumping into the middle of a conversation, but what I meant was that the original text that's been edited here was defined in various Python files:

```
./holoviews/plotting/bokeh/element.py:123:        Rotation angle of the xticks.""")
./holoviews/plotting/mpl/element.py:95:        Rotation angle of the xticks.""")
./holoviews/plotting/mpl/element.py:98:        Rotation angle of the xticks.""")
./holoviews/plotting/mpl/plot.py:256:        Rotation angle of the xticks.""")
```

So yes, it does need to be updated in the reference data, as Philipp is suggesting, but _first_ it needs to be updated in the original source code (as the reference data and .html file simply show the help text derived from the source code).  As far as I can tell, the Python source hasn't been fixed yet, but maybe it's in a PR somewhere I haven't seen.

**Comment by philippjfr** [comment]
The issue is in how to deal with PRs that break the notebook tests. For non-core developers the process is a bit of a nightmare, as they'll have:

1) Submit the original PR on holoviews.
2) Submit a PR against this repository with the updated reference_data.
3) Wait for the PR on this repository to be merged.
4) Update the submodule in the PR on holoviews.

Don't see a way around it though.

**Comment by jbednar** [comment]
Maybe in cases like that they should just post diffs for us to apply and deal with?  The underlying changes are tiny...

**Comment by philippjfr** [comment]
That's true in this case but won't work if any actual visual or data output has changed. We might even have user-contributed Tutorials in which case they'd have to send us the data and visual output for an entire notebook. I'll write up some instructions for developers that describe the process for updating the reference_data and post it to the README on this branch and the HoloViews wiki, eventually we can add a developer instructions page to the website. For now we can maintain a policy where as long as we know a PR on holoviews results results in very well defined changes to the notebook tests, we'll merge it and update the tests ourself.

**Comment by jbednar** [comment]
Ok.  Meanwhile, should Max submit a PR changing the .py files, or should we just handle it ourselves?  I'm happy to do it, but it will break the tests, and I'm _not_ happy to update the reference data using the above process. :-/

**Comment by philippjfr** [comment]
I'll update the tests this time, another issue is that the tests only work with very specific versions of some libraries so I have to ssh into my office machine to do it. Definitely needs streamlining.

**Comment by maxalbert** [comment]
@jbednar The original `.py` files were updated in my recent PR against Holoviews (see [here](https://github.com/maxalbert/holoviews/commit/445dbb213b391db6026c3d26a4d63d1e43ca2fba). This is what caused the Holoviews tests to fail (because the output was different from the reference output), which then triggered me to submit this PR in an attempt to fix the tests.

What I didn't realise is that I'd also need to update the submodule in the PR on Holoviews (@philippjfr's step 4 above). I agree that the whole process isn't exactly simple... :-/

**Comment by jlstevens** [comment]
I'm working on a vastly improved infrastructure [here](https://github.com/ioam/holoviews/pull/429). Hopefully, no one will need to touch this repository themselves anymore!

**Comment by jlstevens** [comment]
As I am currently using the new infrastructure which seems to be working well, I'll now close this issue. Same for #1!

**Pull request closed without merging**
